# Generated by Django 5.0.13 on 2025-11-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='livestock',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.owner'),
        ),
    ]
